project:
  type: website
  output-dir: docs

website:
  title: "lab01_website"
  favicon: img\logo.png  # Provide the path to your favicon file
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: FYP.qmd  # Assuming you have a page for the FYP Project
        text: FYP Project
      - href: about.qmd  # Assuming this is your additional page
        text: About me

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
